### ISSUE TITLE
Company settings - loading gif

### ISSUE THREAD

**Issue by dan-omniscience** [adam2314/linet3#612] opened 2015-12-27 15:03 UTC
Why is the loading gif is showing in the currency and in the vat sections?
http://awesomescreenshot.com/0495ifqn80

**Comment by adam2314** [comment] 2015-12-27 16:47
probably a javascript error i cant reproduce the problem can you open the dev tools and take a look?

**Comment by adam2314** [comment] 2015-12-29 16:41
i wold love to close this issue @dan-omniscience ? what do you say?

**Closed** 2016-01-03 15:50 UTC
